server:
  port: 10003
  servlet:
    context-path: /

spring:
  application:
    name: turbine
  profiles:
    active: development

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:10001/eureka}
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health

turbine:
  cluster-name-expression: new String('default')
  app-config: user, loan, card