server:
  port: 11000
  servlet:
    context-path: /

spring:
  application:
    name: user
  profiles:
    active: development

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:10001/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${server.servlet.context-path}actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}actuator/health

logging:
  level:
    com.koreacb.msa: debug

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
