server:
  port: 11000
  servlet:
    context-path: /

spring:
  application:
    name: user
  profiles:
    active: development

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${server.servlet.context-path}/info
    healthCheckUrlPath: ${server.servlet.context-path}/health
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.koreacb.msa: debug
