server:
  port: 12000
  servlet:
    context-path: /


spring:
  application:
    name: card
  profiles:
    active: development

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:10001/eureka}
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${server.servlet.context-path}/info
    healthCheckUrlPath: ${server.servlet.context-path}/health

logging:
  level:
    com.koreacb.msa: debug

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
