eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:10001/eureka}
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${server.servlet.context-path}actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}actuator/health

logging:
  level:
    com.koreacb.msa: debug

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  type-aliases-package: com.koreacb.msa.card.model
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


