server:
  port: 10004
  servlet:
    context-path: /


spring:
  application:
    name: gateway
  profiles:
    active: development
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:10001/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${server.servlet.context-path}actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}actuator/health

logging:
  level:
    com.koreacb.msa: debug

zuul:
  routes:
    user:
      path: /users/**
      stripPrefix: false
    loan:
      path: /loans/**
      stripPrefix: false
    card:
      path: /cards/**
      stripPrefix: false

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
