server:
  port: 18080
  servlet:
    context-path: /


spring:
  application:
    name: gateway
  profiles:
    active: development
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${server.servlet.context-path}/info
    healthCheckUrlPath: ${server.servlet.context-path}/health

logging:
  level:
    com.koreacb.msa: debug

zuul:
  routes:
    user:
      path: /users/**
      stripPrefix: false
    loan:
      path: /loans/**
      stripPrefix: false
    card:
      path: /cards/**
      stripPrefix: false
