server:
  port: 10005
  servlet:
    context-path: /

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/korea-credit-bureau/config-repository

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:10001/eureka}

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"