server:
  port: 10005
  servlet:
    context-path: /

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:10001/eureka}
 
